name: first workflow

on: workflow_dispatch

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install cowsay
        run: sudo apt-get install cowsay -y

      - name: generate ASCII artwork
        run: cowsay -f dragon "run for cover, i am a dragon" >> dragon.txt

      - name: upload dragon text file
        uses: actions/upload-artifact@v4
        with:
            name: dragon
            path: dragon.txt

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: download dragon text file
        uses: actions/download-artifact@v4
        with:
            name: dragon
          


      - name: sleep for 10 sec
        run: sleep 10

      - name: test file exist
        run: grep -i "dragon" dragon.txt

  deploy_job:
    needs: [build_job,test_job]
    runs-on: ubuntu-latest
    steps:

      - name: download dragon text file
        uses: actions/download-artifact@v4
        with:
            name: dragon
           


      - name: read file
        run: cat dragon.txt
        
      - name: list repo files
        run: ls -ltra

      - name: deploy
        run: echo deployiong .......



