name: first workflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: list and read files
        run: |
          echo "my first workflow"
          ls 
          cat README.md
      - name: generate ASCII artwork
        run: cowsay -f dragon "run for cover, i am a dragon" >> dragon.txt

